### ISSUE TITLE
pasting and hitting del or backspace

### ISSUE THREAD

**Issue by pkra** [fbreuer/qute-html5#38]
When I paste text , the next time I hit del or backspace, the cursor will do del/backspace at at the end of the line, not where it's actually at.

Sometimes, writing some more stuff helps, but not always. I thought it had something to do with the preview, but even switching paragraphs does not prevent this -- the next time I get back to the paragraph I pasted into, the first del/backspace will happen to the end of the line.

That is really annoying :(

**Comment by fbreuer** [comment]
Yes, I can reproduce that. And it _is_ annoying :)

**Comment by fbreuer** [comment]
fixed
