### ISSUE TITLE
desk-theme css problem

### ISSUE THREAD

**Issue by pkra** [fbreuer/qute-html5#43]
I noticed that the desk-theme has white hyperlinks -- white on white that is...

Also, in split view the entire background is white. I don't know if there's a solution for that -- I guess the theme tries to imitate paper on wooden desk but in split view it's two paper next to each other and no room to see the desk.

**Comment by fbreuer** [comment]
will fix the white hyperlinks problem.

as I plan to remove the split view in Qute 0.5, the split view problem will not get fixed.

**Comment by fbreuer** [comment]
color problem fixed
