### ISSUE TITLE
pandoc integration

### ISSUE THREAD

**Issue by fbreuer** [fbreuer/qute-html5#45]
pandoc integration would be desirable for various reasons. especially because printing does not really work, due to bugs in gecko (disappearing math characters).

the plan: add a "compile with pandoc" publishing option that only works if the user has pandoc installed.

if the implementation is as quick and easy as I think, this should be done for 0.4. otherwise after 0.5.

**Comment by pkra** [comment]
If it was possible to switch the mathjax rendering mechanism to png-fonts, printing would most likely be fine.

On the other hand, if you stick with the (better) mathml rendering, you might as well remove all the fonts from mathjax -- making it more like 1.5MB and 100 files...

**Comment by fbreuer** [comment]
- Unfortunately, png fonts don't help on Windows. PDF printed from Firefox
  in this way have terribly pixelated formulas.
- I already did remove the png font from MathJax (since release 0.1). In
  fact, if I added the png fonts back in, the releases would not fit in my
  GitHub quota :)

2011/9/28 pkra <
reply@reply.github.com>

> If it was possible to switch the mathjax rendering mechanism to png-fonts,
> printing would most likely be fine.
> 
> On the other hand, if you stick with the (better) mathml rendering, you
> might as well remove all the fonts from mathjax -- making it more like 1.5MB
> and 100 files...
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fbreuer/qute-html5/issues/45#issuecomment-2226777

## 

http://www.felixbreuer.net

**Comment by pkra** [comment]
One more thought: if you integrate pandoc, you might as well drop mathjax completely.

Pandoc converts markdown+TeXcode to html+mathml very nicely. Of course, you could turn Qute into the Pandoc-equivalent of the LaTeX editor Gummi... That would be pretty awesome, too.

**Comment by fbreuer** [comment]
I see your point, but I don't really want to ship pandoc with Qute. Also,
pandoc may be slower than mathjax, but we will have to see about that.

Re Gummi: I really want to go in a different direction with Qute. :)

2011/10/3 pkra <
reply@reply.github.com>

> One more thought: if you integrate pandoc, you might as well drop mathjax
> completely.
> 
> Pandoc converts markdown+TeXcode to html+mathml very nicely. Of course, you
> could turn Qute into the Pandoc-equivalent of the LaTeX editor Gummi... That
> would be pretty awesome, too.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fbreuer/qute-html5/issues/45#issuecomment-2273155

## 

http://www.felixbreuer.net

**Comment by fbreuer** [comment]
Qute now has Pandoc export functionality.
